name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-backend:
    name: Install composer deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2
      - name: Install composer deps
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Upload composer vendor
        uses: actions/upload-artifact@v4
        with:
          name: composer-vendor
          path: vendor

  build-frontend:
    name: build frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2
      - name: Download composer vendor
        uses: actions/download-artifact@v4
        with:
          name: composer-vendor
          path: ./vendor
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build app
        run: npm run build
      - name: Upload Vue build
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: public/build

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [ build-frontend, build-backend ]
    steps:
      - uses: actions/checkout@v3
      - name: Download Vue build
        uses: actions/download-artifact@v4
        with:
          name: vue-dist
          path: ./public/build

      - name: Download composer vendor
        uses: actions/download-artifact@v4
        with:
          name: composer-vendor
          path: ./vendor

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rojan-grasser
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha }}

  tag-docker-image:
    name: Tag docker image
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rojan-grasser
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "FROM ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha }}" > Dockerfile

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.release.outputs.new_release_version }}
